//------------------------------------------------------------------------------
// <auto-generated>
//     Der Code wurde von einer Vorlage generiert.
//
//     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
//     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ludothek.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class AusleiheSpiel
    {
        public System.Guid ID { get; set; }
        public System.Guid FkAusleihe { get; set; }
        public System.Guid FkSpiel { get; set; }
    
        public virtual Ausleihe Ausleihe { get; set; }
        public virtual Spiel Spiel { get; set; }
    }
}
