//------------------------------------------------------------------------------
// <auto-generated>
//     Der Code wurde von einer Vorlage generiert.
//
//     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
//     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ludothek.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ausleihe
    {
        public System.Guid ID { get; set; }
        public int Nummer { get; set; }
        public int SpielNummer { get; set; }
        public string SpielBezeichnung { get; set; }
        public string Verlag { get; set; }
        public System.DateTime Ausleihdatum { get; set; }
        public Nullable<System.DateTime> Rueckgabedatum { get; set; }
        public int AnzVerlängerungen { get; set; }
        public System.Guid FkKunde { get; set; }
    
        public virtual Kunde Kunde { get; set; }
    }
}
