//------------------------------------------------------------------------------
// <auto-generated>
//     Der Code wurde von einer Vorlage generiert.
//
//     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
//     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ludothek.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ausleihe
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Ausleihe()
        {
            this.AusleiheSpiel = new HashSet<AusleiheSpiel>();
        }
    
        public System.Guid ID { get; set; }
        public Nullable<int> Ausleihnummer { get; set; }
        public Nullable<System.DateTime> Ausleihdatum { get; set; }
        public Nullable<System.DateTime> Rückgabedatum { get; set; }
        public Nullable<int> AnzVerlängerungen { get; set; }
        public System.Guid FkKunde { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AusleiheSpiel> AusleiheSpiel { get; set; }
        public virtual Kunde Kunde { get; set; }
    }
}
