//------------------------------------------------------------------------------
// <auto-generated>
//     Der Code wurde von einer Vorlage generiert.
//
//     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
//     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ludothek.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class LudothekDBEntities : DbContext
    {
        public LudothekDBEntities()
            : base("name=LudothekDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Ausleihe> Ausleihe { get; set; }
        public virtual DbSet<Kunde> Kunde { get; set; }
        public virtual DbSet<Ludothek> Ludothek { get; set; }
        public virtual DbSet<Mitarbeiter> Mitarbeiter { get; set; }
        public virtual DbSet<Spiel> Spiel { get; set; }
        public virtual DbSet<Spielkategorie> Spielkategorie { get; set; }
        public virtual DbSet<Standort> Standort { get; set; }
        public virtual DbSet<Tarifkategorie> Tarifkategorie { get; set; }
        public virtual DbSet<Verband> Verband { get; set; }
        public virtual DbSet<Verbandsvorstandsmitarbeiter> Verbandsvorstandsmitarbeiter { get; set; }
        public virtual DbSet<Verlag> Verlag { get; set; }
    }
}
