//------------------------------------------------------------------------------
// <auto-generated>
//     Der Code wurde von einer Vorlage generiert.
//
//     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
//     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ludothek.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Mitarbeiter
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Mitarbeiter()
        {
            this.Verbandsvorstandsmitarbeiter = new HashSet<Verbandsvorstandsmitarbeiter>();
        }
    
        public System.Guid ID { get; set; }
        public Nullable<int> Personalnummer { get; set; }
        public string Vorname { get; set; }
        public string Nachname { get; set; }
        public Nullable<System.DateTime> Geburtsdatum { get; set; }
        public Nullable<System.Guid> FkLudothek { get; set; }
    
        public virtual Ludothek Ludothek { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Verbandsvorstandsmitarbeiter> Verbandsvorstandsmitarbeiter { get; set; }
    }
}
