//------------------------------------------------------------------------------
// <auto-generated>
//     Der Code wurde von einer Vorlage generiert.
//
//     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
//     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ludothek.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Mitarbeiter
    {
        public System.Guid ID { get; set; }
        public Nullable<int> Personalnummer { get; set; }
        public Nullable<System.Guid> FK_Ludothek_ID { get; set; }
        public Enums.Funktion Funktion { get; set; }
        public System.Guid FK_Benutzer_ID { get; set; }
    
        public virtual Benutzer Benutzer { get; set; }
        public virtual Ludothek Ludothek { get; set; }
    }
}
