//------------------------------------------------------------------------------
// <auto-generated>
//     Der Code wurde von einer Vorlage generiert.
//
//     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
//     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ludothek.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Spiel
    {
        public System.Guid ID { get; set; }
        public int Spielnummer { get; set; }
        public string Name { get; set; }
        public System.Guid FkVerlag { get; set; }
        public System.Guid FkSpielkategorie { get; set; }
        public System.Guid FkTarifkategorie { get; set; }
        public string Beschreibung { get; set; }
        public Nullable<int> FSK { get; set; }
    
        public virtual Spielkategorie Spielkategorie { get; set; }
        public virtual Tarifkategorie Tarifkategorie { get; set; }
        public virtual Verlag Verlag { get; set; }
    }
}
