//------------------------------------------------------------------------------
// <auto-generated>
//     Der Code wurde von einer Vorlage generiert.
//
//     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
//     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ludothek.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Standort
    {
        public System.Guid ID { get; set; }
        public Nullable<int> PLZ { get; set; }
        public string Name { get; set; }
        public System.Guid FK_Ludothek_ID { get; set; }
    
        public virtual Ludothek Ludothek { get; set; }
    }
}
