//------------------------------------------------------------------------------
// <auto-generated>
//     Der Code wurde von einer Vorlage generiert.
//
//     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
//     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ludothek.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Verbandsvorstandsmitarbeiter
    {
        public System.Guid ID { get; set; }
        public System.Guid FkMitarbeiter { get; set; }
        public System.Guid FkVerband { get; set; }
    
        public virtual Mitarbeiter Mitarbeiter { get; set; }
        public virtual Verband Verband { get; set; }
    }
}
